#!/bin/bash
# script used to clean up any file in the temporary
# directory and the script file if its empty
#
# part of the iGMT package, see COPYRIGHT for description
# and license
# 
# $Id: igmt_helper_rmtmp_silent,v 1.3 2001/08/07 18:50:44 becker Exp becker $
#
rm /tmp/igmt_$USER* 2> /dev/null
if [ $# -ne 0 ]; then
    if [[ -a $1 && ! -s $1  ]] # this line to remove the parameter file, if its empty
    then 
        rm $1 2> /dev/null
    fi
    rm $2 $3 $4 $5 $6 $7 $8 $9 $10 2> /dev/null
fi


